/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-extras_uBuntu22_04
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_EXTRAS_UBUNTU22_04_API_H
#define INCLUDED_EXTRAS_UBUNTU22_04_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_extras_uBuntu22_04_EXPORTS
#define EXTRAS_UBUNTU22_04_API __GR_ATTR_EXPORT
#else
#define EXTRAS_UBUNTU22_04_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_EXTRAS_UBUNTU22_04_API_H */
